drop DATABASE BDCADASTRO

USE BDCADASTRO



CREATE TABLE CONTATO (
	ID INT NOT NULL IDENTITY,
	NOME VARCHAR (50) NOT NULL,
	CELULAR VARCHAR (15),
	EMPRESA VARCHAR(50),
	EMAIL VARCHAR (50),
	RESIDENCIAL VARCHAR (15),
	CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
	)

	SELECT * FROM tbCONTATO
